name: RUN_SERVER

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  MongoDBUserName: ${{ secrets.MongoDBUserName }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clear Yarn cache (if exists)
        run: |
          if [ -d ~/.cache/yarn ]; then
            echo "Clearing Yarn cache"
            yarn cache clean
          fi
      - run: yarn install
      - run: yarn run test --passWithNoTests